
@echo off

REM !!! Generated by the fmp-cli 1.83.0.  DO NOT EDIT!

md MeeMake\Assets\3rd\fmp-xtc-meemake

cd ..\vs2022
dotnet build -c Release

copy fmp-xtc-meemake-lib-mvcs\bin\Release\netstandard2.1\*.dll ..\unity2021\MeeMake\Assets\3rd\fmp-xtc-meemake\
